#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/env.sh
mkdir -p bin .keys
target="${1:-app-production}"

case "$target" in
  app|app-production)
    jungle="monkey.jungle"
    output="bin/rad_monitor-app-production.prg"
    generate_build_info=true
    ;;
  app-beta)
    jungle="monkey-beta.jungle"
    output="bin/rad_monitor-app-beta.prg"
    generate_build_info=true
    ;;
  field|field-production)
    jungle="datafield/monkey.jungle"
    output="bin/rad_monitor-field-production.prg"
    generate_build_info=false
    ;;
  field-beta)
    jungle="datafield/monkey-beta.jungle"
    output="bin/rad_monitor-field-beta.prg"
    generate_build_info=false
    ;;
  test)
    jungle="tests.jungle"
    output="bin/rad_monitor-tests.prg"
    generate_build_info=true
    ;;
  field-test)
    jungle="datafield/tests.jungle"
    output="bin/rad_monitor-field-tests.prg"
    generate_build_info=false
    ;;
  *)
    echo "Usage: $0 {app-production|app-beta|field-production|field-beta|test|field-test}" >&2
    exit 2
    ;;
esac

if [[ "$generate_build_info" == true ]]; then
  build_time="$(date -u +%Y-%m-%dT%H:%MZ)"
  cat > source/BuildInfo.mc <<BUILD
// Generated by scripts/build.sh; UTC build identity shown in Info.
module BuildInfo {
    const VERSION="0.3.3";
    const BUILT="$build_time";
    const SDK="9.2.0";
}
BUILD
fi
key="${CIQ_DEVELOPER_KEY:-$PWD/.keys/developer_key.der}"
if [[ ! -f "$key" ]]; then
  if [[ -n "${CIQ_DEVELOPER_KEY:-}" ]]; then echo "Signing key not found: $key" >&2; exit 1; fi
  (umask 077; openssl genrsa 4096 2>/dev/null | openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -out "$key")
fi

if [[ "$target" == test || "$target" == field-test ]]; then
  monkeyc -f "$jungle" -d instinct3solar45mm -y "$key" -o "$output" -t -w
else
  monkeyc -f "$jungle" -d instinct3solar45mm -y "$key" -o "$output" -w --build-stats 0
fi
