#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/env.sh
mkdir -p bin .keys
build_time="$(date -u +%Y-%m-%dT%H:%MZ)"
cat > source/BuildInfo.mc <<BUILD
// Generated by scripts/build.sh; UTC build identity shown in Info.
module BuildInfo {
    const VERSION="0.3.1";
    const BUILT="$build_time";
    const SDK="9.2.0";
}
BUILD
key="${CIQ_DEVELOPER_KEY:-$PWD/.keys/developer_key.der}"
if [[ ! -f "$key" ]]; then
  if [[ -n "${CIQ_DEVELOPER_KEY:-}" ]]; then echo "Signing key not found: $key" >&2; exit 1; fi
  (umask 077; openssl genrsa 4096 2>/dev/null | openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -out "$key")
fi
if [[ "${1:-}" == test ]]; then
  monkeyc -f tests.jungle -d instinct3solar45mm -y "$key" -o bin/rad_monitor-tests.prg -t -w
else
  monkeyc -f monkey.jungle -d instinct3solar45mm -y "$key" -o bin/rad_monitor.prg -w --build-stats 0
fi
